### ISSUE TITLE
リンク先でアクセス拒否される

### ISSUE THREAD

**Issue by ikisuke** [wagumi/sbt#172]
https://github.com/wagumi/sbt/blob/c3dc0463f95669d4a3d653dfcd9e9d2f6d01f069/metadata/937906941257199667.json#L40
![image](https://user-images.githubusercontent.com/46296566/226160441-399d1ac0-8a0b-4965-ac4a-2f68e834d0e8.png)

**Comment by ikisuke** [comment]
notion://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F4add1bd8-fa04-47de-90d5-edafa26f3ea1%2Fd59319-61-1d73ef6cce36dc04d843-1.jpg?table=block&id=a89eda4d-15a0-4161-8e98-cc7f2997c358&spaceId=ebf9bee6-384e-4fc2-a172-bb5572209af8&width=600&userId=81e92e89-2cb4-47c7-9b03-6fcf50ba14ea&cache=v2
該当imageをNotionのDBから直接リンクとして取得した場合。
Notionにリダイレクトされるようになる。

**Comment by tksohishi** [comment]
Twitterに上がってるやつとかを使えば楽かなと思いましたｗ
https://pbs.twimg.com/media/FXI-GoXVEAItzIv?format=jpg&name=large

**Comment by ikisuke** [comment]
@tksohishi 
確かにw
Notionの画像をTwitterのものに変更しました！

**Comment by tksohishi** [comment]
一旦closeしますー
